export default [
    {
        name: "UNIT AMC",
        icon: "car-outline",
        bgColor: "#B91C1C",
        route: "/amc",
        childrenMenu: [
            {
                name: "DASHBOARD MONITORING",
                icon: "bar-chart-outline",
                bgColor: "#DC2626",
                route: "",
            },
            {
                name: "INITIAL SCHEDULED",
                icon: "timer-outline",
                bgColor: "bg-orange-400",
                route: "/initial-scheduled",
            },
            {
                name: "INITIAL UNSCEDULED",
                icon: "alarm-outline",
                bgColor: "bg-cyan-400",
                route: "/initial-unscheduled",
            },
            {
                name: "LOG BOOK",
                icon: "book-outline",
                bgColor: "bg-lime-400",
                route: "/logbook",
            },
            {
                name: "LANDED",
                icon: "book-outline",
                bgColor: "bg-lime-400",
                route: "/landed",
            },
            {
                name: "TAKEOFF",
                icon: "book-outline",
                bgColor: "bg-lime-400",
                route: "/takeoff",
            },
            {
                name: "CANCELLED",
                icon: "book-outline",
                bgColor: "bg-lime-400",
                route: "/cancelled",
            },
            {
                name: "ALL FLIGHT",
                icon: "book-outline",
                bgColor: "bg-lime-400",
                route: "/all-flight",
            },
            
            {
                name: "PARKING STAND",
                icon: "people-outline",
                bgColor: "bg-pink-400",
                route: "/parking-stand",
            },
            {
                name: "OPERATOR",
                icon: "calendar-outline",
                bgColor: "bg-amber-400",
                route: "/operator",
            },
            {
                name: "FLIGHT TYPE",
                icon: "folder-outline",
                bgColor: "bg-indigo-400",
                route: "/flight-type",
            },
            {
                name: "AIRPORT",
                icon: "folder-outline",
                bgColor: "bg-indigo-400",
                route: "/airport",
            },
        ],
    },
    {
        name: "UNIT ELBAN",
        icon: "airplane-outline",
        bgColor: "#1D4ED8", 
        route: "/elban",
        childrenMenu: [
            {
                name: "FASILITAS",
                icon: "bed-outline",
                bgColor: "bg-pink-500",
                route: "/fasilitas",
            },
            {
                name: "PERALATAN",
                icon: "construct-outline",
                bgColor: "bg-cyan-500",
                route: "/peralatan",
            },
            {
                name: "PEMELIHARAAN",
                icon: "hammer-outline",
                bgColor: "bg-lime-500",
                route: "/pemeliharaan",
            },
            {
                name: "LOG BOOK",
                icon: "book-outline",
                bgColor: "bg-indigo-500",
                route: "/logbook",
            },
            {
                name: "SOP",
                icon: "clipboard-outline",
                bgColor: "bg-red-500",
                route: "/sop",
            },
            {
                name: "KERUSAKAN",
                icon: "alert-circle-outline",
                bgColor: "bg-orange-500",
                route: "/kerusakan",
            },
            {
                name: "PERBAIKAN",
                icon: "build-outline",
                bgColor: "bg-purple-500",
                route: "/perbaikan",
            },
            {
                name: "SUKU CADANG",
                icon: "cube-outline",
                bgColor: "bg-amber-500",
                route: "/sukucadang",
            },
            {
                name: "PERSONIL",
                icon: "people-outline",
                bgColor: "bg-emerald-500",
                route: "/personil",
            },
            {
                name: "PENGADAAN",
                icon: "cart-outline",
                bgColor: "bg-rose-500",
                route: "/pengadaan",
            },
            {
                name: "JADWAL DINAS",
                icon: "calendar-outline",
                bgColor: "bg-teal-500",
                route: "/jadwaldinas",
            },
            {
                name: "DATA MANAGEMENT",
                icon: "folder-outline",
                bgColor: "bg-fuchsia-500",
                route: "/datamanagement",
            },
        ],
    },
    {
        name: "UNIT LISTRIK",
        icon: "flash-outline",
        bgColor: "#047857",      // warna parent
        route: "/listrik",
        childrenMenu: [
            {
                name: "FASILITAS",
                icon: "bed-outline",
                bgColor: "bg-blue-500",
                route: "/fasilitas",
            },
            {
                name: "PERALATAN",
                icon: "construct-outline",
                bgColor: "bg-pink-500",
                route: "/peralatan",
            },
            {
                name: "PEMELIHARAAN",
                icon: "hammer-outline",
                bgColor: "bg-lime-500",
                route: "/listrik/pemeliharaan",
            },
            {
                name: "LOG BOOK",
                icon: "book-outline",
                bgColor: "bg-indigo-500",
                route: "/listrik/logbook",
            },
            {
                name: "SOP",
                icon: "clipboard-outline",
                bgColor: "bg-red-500",
                route: "/listrik/sop",
            },
            {
                name: "KERUSAKAN",
                icon: "alert-circle-outline",
                bgColor: "bg-orange-500",
                route: "/listrik/kerusakan",
            },
            {
                name: "PERBAIKAN",
                icon: "build-outline",
                bgColor: "bg-purple-500",
                route: "/listrik/perbaikan",
            },
            {
                name: "SUKU CADANG",
                icon: "cube-outline",
                bgColor: "bg-amber-500",
                route: "/listrik/sukucadang",
            },
            {
                name: "PERSONIL",
                icon: "people-outline",
                bgColor: "bg-emerald-500",
                route: "/listrik/personil",
            },
            {
                name: "PENGADAAN",
                icon: "cart-outline",
                bgColor: "bg-rose-500",
                route: "/listrik/pengadaan",
            },
            {
                name: "JADWAL DINAS",
                icon: "calendar-outline",
                bgColor: "bg-teal-500",
                route: "/listrik/jadwaldinas",
            },
            {
                name: "DATA MANAGEMENT",
                icon: "folder-outline",
                bgColor: "bg-fuchsia-500",
                route: "/listrik/datamanagement",
            },
        ],
    },
    {
        name: "UNIT BANGLAND",
        icon: "business-outline",
        bgColor: "#C2410C",     // warna parent
        route: "/portal-bangland",
        childrenMenu: [
            {
                name: "FASILITAS",
                icon: "bed-outline",
                bgColor: "bg-blue-500",
                route: "/bangland/fasilitas",
            },
            {
                name: "PERALATAN",
                icon: "construct-outline",
                bgColor: "bg-pink-500",
                route: "/bangland/peralatan",
            },
            {
                name: "PEMELIHARAAN",
                icon: "hammer-outline",
                bgColor: "bg-lime-500",
                route: "/bangland/pemeliharaan",
            },
            {
                name: "LOG BOOK",
                icon: "book-outline",
                bgColor: "bg-indigo-500",
                route: "/bangland/logbook",
            },
            {
                name: "SOP",
                icon: "clipboard-outline",
                bgColor: "bg-red-500",
                route: "/bangland/sop",
            },
            {
                name: "KERUSAKAN",
                icon: "alert-circle-outline",
                bgColor: "bg-orange-500",
                route: "/bangland/kerusakan",
            },
            {
                name: "PERBAIKAN",
                icon: "build-outline",
                bgColor: "bg-purple-500",
                route: "/bangland/perbaikan",
            },
            {
                name: "SUKU CADANG",
                icon: "cube-outline",
                bgColor: "bg-amber-500",
                route: "/bangland/sukucadang",
            },
            {
                name: "PERSONIL",
                icon: "people-outline",
                bgColor: "bg-emerald-500",
                route: "/bangland/personil",
            },
            {
                name: "PENGADAAN",
                icon: "cart-outline",
                bgColor: "bg-rose-500",
                route: "/bangland/pengadaan",
            },
            {
                name: "JADWAL DINAS",
                icon: "calendar-outline",
                bgColor: "bg-teal-500",
                route: "/bangland/jadwaldinas",
            },
            {
                name: "DATA MANAGEMENT",
                icon: "folder-outline",
                bgColor: "bg-fuchsia-500",
                route: "/bangland/datamanagement",
            },
        ],
    },
    {
        name: "UNIT A2B",
        icon: "document-text-outline",
        bgColor: "#6D28D9",     // warna parent
        route: "/portal-a2b",
        childrenMenu: [
            {
                name: "FASILITAS",
                icon: "bed-outline",
                bgColor: "bg-blue-500",
                route: "/a2b/fasilitas",
            },
            {
                name: "PERALATAN",
                icon: "construct-outline",
                bgColor: "bg-pink-500",
                route: "/a2b/peralatan",
            },
            {
                name: "PEMELIHARAAN",
                icon: "hammer-outline",
                bgColor: "bg-lime-500",
                route: "/a2b/pemeliharaan",
            },
            {
                name: "LOG BOOK",
                icon: "book-outline",
                bgColor: "bg-indigo-500",
                route: "/a2b/logbook",
            },
            {
                name: "SOP",
                icon: "clipboard-outline",
                bgColor: "bg-red-500",
                route: "/a2b/sop",
            },
            {
                name: "KERUSAKAN",
                icon: "alert-circle-outline",
                bgColor: "bg-orange-500",
                route: "/a2b/kerusakan",
            },
            {
                name: "PERBAIKAN",
                icon: "build-outline",
                bgColor: "bg-purple-500",
                route: "/a2b/perbaikan",
            },
            {
                name: "SUKU CADANG",
                icon: "cube-outline",
                bgColor: "bg-amber-500",
                route: "/a2b/sukucadang",
            },
            {
                name: "PERSONIL",
                icon: "people-outline",
                bgColor: "bg-emerald-500",
                route: "/a2b/personil",
            },
            {
                name: "PENGADAAN",
                icon: "cart-outline",
                bgColor: "bg-rose-500",
                route: "/a2b/pengadaan",
            },
            {
                name: "JADWAL DINAS",
                icon: "calendar-outline",
                bgColor: "bg-teal-500",
                route: "/a2b/jadwaldinas",
            },
            {
                name: "DATA MANAGEMENT",
                icon: "folder-outline",
                bgColor: "bg-fuchsia-500",
                route: "/a2b/datamanagement",
            },
        ],
    },
    
]