import {Images} from '@/config';
import * as Utils from '@/utils';

export const getReview = async ({params}) => {
  await Utils.delay(1000);
  return {
    success: true,
    attr: {
      rating: {
        rating_avg: 3.3,
        rating_count: 8,
        rating_meta: {
          1: 2,
          2: 1,
          3: 1,
          4: 1,
          5: 3,
        },
      },
    },
    data: [
      {
        comment_ID: '513',
        comment_post_ID: '1206',
        comment_author: 'PassionUI',
        comment_author_email: 'paul.passionui@gmail.com',
        comment_author_url: '',
        comment_author_IP: '49.173.47.74',
        comment_date: '2020-08-16 18:27:55',
        comment_date_gmt: '2020-08-16 10:27:55',
        comment_content:
          'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas',
        comment_karma: '0',
        comment_approved: '1',
        comment_agent: '',
        comment_type: '',
        comment_parent: '0',
        user_id: '1',
        comment_author_image: Images.avata3,
        rate: '4',
      },
      {
        comment_ID: '514',
        comment_post_ID: '1206',
        comment_author: 'PassionUI',
        comment_author_email: 'paul.passionui@gmail.com',
        comment_author_url: '',
        comment_author_IP: '43.244.190.208',
        comment_date: '2020-08-16 18:27:55',
        comment_date_gmt: '2020-08-16 10:27:55',
        comment_content:
          'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin',
        comment_karma: '0',
        comment_approved: '1',
        comment_agent: '',
        comment_type: '',
        comment_parent: '0',
        user_id: '1',
        comment_author_image: Images.avata3,
        rate: '1',
      },
      {
        comment_ID: '515',
        comment_post_ID: '1206',
        comment_author: 'PassionUI',
        comment_author_email: 'paul.passionui@gmail.com',
        comment_author_url: '',
        comment_author_IP: '143.120.168.157',
        comment_date: '2020-08-16 18:27:55',
        comment_date_gmt: '2020-08-16 10:27:55',
        comment_content:
          'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus',
        comment_karma: '0',
        comment_approved: '1',
        comment_agent: '',
        comment_type: '',
        comment_parent: '0',
        user_id: '1',
        comment_author_image: Images.avata3,
        rate: '1',
      },
      {
        comment_ID: '516',
        comment_post_ID: '1206',
        comment_author: 'PassionUI',
        comment_author_email: 'paul.passionui@gmail.com',
        comment_author_url: '',
        comment_author_IP: '186.49.89.156',
        comment_date: '2020-08-16 18:27:55',
        comment_date_gmt: '2020-08-16 10:27:55',
        comment_content:
          'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus',
        comment_karma: '0',
        comment_approved: '1',
        comment_agent: '',
        comment_type: '',
        comment_parent: '0',
        user_id: '1',
        comment_author_image: Images.avata3,
        rate: '5',
      },
      {
        comment_ID: '517',
        comment_post_ID: '1206',
        comment_author: 'PassionUI',
        comment_author_email: 'paul.passionui@gmail.com',
        comment_author_url: '',
        comment_author_IP: '125.131.117.37',
        comment_date: '2020-08-16 18:27:55',
        comment_date_gmt: '2020-08-16 10:27:55',
        comment_content:
          'malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum',
        comment_karma: '0',
        comment_approved: '1',
        comment_agent: '',
        comment_type: '',
        comment_parent: '0',
        user_id: '1',
        comment_author_image: Images.avata3,
        rate: '5',
      },
      {
        comment_ID: '518',
        comment_post_ID: '1206',
        comment_author: 'PassionUI',
        comment_author_email: 'paul.passionui@gmail.com',
        comment_author_url: '',
        comment_author_IP: '138.108.214.133',
        comment_date: '2020-08-16 18:27:55',
        comment_date_gmt: '2020-08-16 10:27:55',
        comment_content:
          'ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia',
        comment_karma: '0',
        comment_approved: '1',
        comment_agent: '',
        comment_type: '',
        comment_parent: '0',
        user_id: '1',
        comment_author_image: Images.avata3,
        rate: '5',
      },
      {
        comment_ID: '519',
        comment_post_ID: '1206',
        comment_author: 'PassionUI',
        comment_author_email: 'paul.passionui@gmail.com',
        comment_author_url: '',
        comment_author_IP: '107.132.217.19',
        comment_date: '2020-08-16 18:27:55',
        comment_date_gmt: '2020-08-16 10:27:55',
        comment_content:
          'justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam',
        comment_karma: '0',
        comment_approved: '1',
        comment_agent: '',
        comment_type: '',
        comment_parent: '0',
        user_id: '1',
        comment_author_image: Images.avata3,
        rate: '3',
      },
      {
        comment_ID: '520',
        comment_post_ID: '1206',
        comment_author: 'PassionUI',
        comment_author_email: 'paul.passionui@gmail.com',
        comment_author_url: '',
        comment_author_IP: '93.182.61.247',
        comment_date: '2020-08-16 18:27:55',
        comment_date_gmt: '2020-08-16 10:27:55',
        comment_content:
          'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero',
        comment_karma: '0',
        comment_approved: '1',
        comment_agent: '',
        comment_type: '',
        comment_parent: '0',
        user_id: '1',
        comment_author_image: Images.avata3,
        rate: '2',
      },
    ],
  };
};
